apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-user
  name: api-user-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: api-user
