apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-feed
  name: api-feed-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/api-feed-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: api-feed
